# Generated by Django 4.1.2 on 2023-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id_air', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('count_sits', models.IntegerField()),
            ],
            options={
                'db_table': 'aircrafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'flights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_flight', models.BigIntegerField()),
                ('seat_number', models.IntegerField()),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
    ]
