# Generated by Django 4.1.2 on 2023-05-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airs', '0002_aircraft_country_ticket'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='countrys',
        ),
    ]
