# Generated by Django 4.1.2 on 2023-05-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('dt_booking_created', models.DateTimeField()),
                ('dt_booking_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='BookingQuota',
            fields=[
                ('id_quota', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('max_quota', models.IntegerField(default=5)),
                ('use_quota', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'booking_quota',
            },
        ),
        migrations.CreateModel(
            name='BookingTicket',
            fields=[
                ('id_ticket', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_booking', models.BigIntegerField()),
            ],
            options={
                'db_table': 'booking_tickets',
            },
        ),
    ]
