# Generated by Django 4.1.2 on 2023-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingticket',
            name='id_flight',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
