# Generated by Django 4.1.2 on 2023-04-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_flight', models.BigIntegerField()),
                ('country_source', models.CharField(max_length=50)),
                ('country_target', models.CharField(max_length=50)),
                ('air_name', models.CharField(max_length=50)),
                ('count_sits', models.IntegerField()),
                ('count_free_tickets', models.IntegerField()),
            ],
            options={
                'db_table': 'v_flight_list',
                'managed': False,
            },
        ),
    ]
