# Generated by Django 4.1.2 on 2023-04-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_flight_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_detail',
            fields=[
                ('id_ticket', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_passenger', models.BigIntegerField()),
                ('id_flight', models.BigIntegerField()),
                ('seat_number', models.IntegerField()),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
    ]
