# Generated by Django 4.1.2 on 2023-04-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_flight_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_quota',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('all_quota', models.IntegerField()),
                ('use_quota', models.IntegerField()),
            ],
            options={
                'db_table': 'booking_quota',
                'managed': False,
            },
        ),
    ]
