--
-- PostgreSQL database dump
--

-- Dumped from database version 14.7
-- Dumped by pg_dump version 14.7

-- Started on 2023-05-22 10:56:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 213 (class 1259 OID 90703)
-- Name: booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking (
    id_booking integer NOT NULL,
    user_name character varying(50) NOT NULL,
    dt_booking_created timestamp without time zone NOT NULL,
    dt_booking_end timestamp without time zone NOT NULL
);


ALTER TABLE public.booking OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 90702)
-- Name: booking_id_booking_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.booking_id_booking_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.booking_id_booking_seq OWNER TO postgres;

--
-- TOC entry 3329 (class 0 OID 0)
-- Dependencies: 212
-- Name: booking_id_booking_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.booking_id_booking_seq OWNED BY public.booking.id_booking;


--
-- TOC entry 210 (class 1259 OID 73741)
-- Name: booking_quota; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking_quota (
    id_quota bigint NOT NULL,
    username character varying(150) NOT NULL,
    max_quota integer DEFAULT 5 NOT NULL,
    use_quota integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.booking_quota OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 73740)
-- Name: booking_quota_id_quota_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.booking_quota ALTER COLUMN id_quota ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_quota_id_quota_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 73753)
-- Name: booking_tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking_tickets (
    id_ticket bigint NOT NULL,
    id_booking bigint NOT NULL,
    id_flight bigint
);


ALTER TABLE public.booking_tickets OWNER TO postgres;

--
-- TOC entry 3175 (class 2604 OID 90706)
-- Name: booking id_booking; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking ALTER COLUMN id_booking SET DEFAULT nextval('public.booking_id_booking_seq'::regclass);


--
-- TOC entry 3323 (class 0 OID 90703)
-- Dependencies: 213
-- Data for Name: booking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.booking (id_booking, user_name, dt_booking_created, dt_booking_end) FROM stdin;
9	user_1	2023-05-21 18:39:00.02085	2023-06-10 18:39:00.02085
10	user_1	2023-05-21 18:39:25.016137	2023-06-10 18:39:25.016137
11	1	2023-05-21 18:42:13.186957	2023-06-10 18:42:13.186957
\.


--
-- TOC entry 3320 (class 0 OID 73741)
-- Dependencies: 210
-- Data for Name: booking_quota; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.booking_quota (id_quota, username, max_quota, use_quota) FROM stdin;
6	user_1	5	3
\.


--
-- TOC entry 3321 (class 0 OID 73753)
-- Dependencies: 211
-- Data for Name: booking_tickets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.booking_tickets (id_ticket, id_booking, id_flight) FROM stdin;
2	9	1
3	10	1
4	10	1
1	11	1
5	11	1
6	11	1
\.


--
-- TOC entry 3330 (class 0 OID 0)
-- Dependencies: 212
-- Name: booking_id_booking_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.booking_id_booking_seq', 11, true);


--
-- TOC entry 3331 (class 0 OID 0)
-- Dependencies: 209
-- Name: booking_quota_id_quota_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.booking_quota_id_quota_seq', 6, true);


--
-- TOC entry 3179 (class 2606 OID 90708)
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (id_booking);


--
-- TOC entry 3177 (class 2606 OID 73747)
-- Name: booking_quota booking_quota_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_quota
    ADD CONSTRAINT booking_quota_pkey PRIMARY KEY (id_quota);


-- Completed on 2023-05-22 10:56:51

--
-- PostgreSQL database dump complete
--

