openapi: 3.0.0
info:
  title: airs API
  version: 1.0.0
paths:
  /api/flights/:
    get:
      summary: Get a list of flights
      operationId: flightList
      responses:
        200:
          description: Successful operation
    post:
      summary: Create a new flight
      operationId: createFlight
      responses:
        201:
          description: Flight created successfully

  /api/flights/{pk}/:
    get:
      summary: Get flight details by ID
      operationId: flightDetail
      parameters:
        - name: pk
          in: path
          description: Flight ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful operation
    put:
      summary: Update flight details
      operationId: updateFlight
      parameters:
        - name: pk
          in: path
          description: Flight ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Flight updated successfully
    delete:
      summary: Delete a flight
      operationId: deleteFlight
      parameters:
        - name: pk
          in: path
          description: Flight ID
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Flight deleted successfully

  /api/flights/{flight_id}/tickets/:
    get:
      summary: Get a list of tickets for a specific flight
      operationId: ticketListByFlight
      parameters:
        - name: flight_id
          in: path
          description: Flight ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful operation

  /api/countrys/:
    get:
      summary: Get a list of countries
      operationId: countryList
      responses:
        200:
          description: Successful operation
    post:
      summary: Create a new country
      operationId: createCountry
      responses:
        201:
          description: Country created successfully

  /api/countrys/{pk}/:
    get:
      summary: Get country details by ID
      operationId: countryDetail
      parameters:
        - name: pk
          in: path
          description: Country ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful operation
    put:
      summary: Update country details
      operationId: updateCountry
      parameters:
        - name: pk
          in: path
          description: Country ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Country updated successfully
    delete:
      summary: Delete a country
      operationId: deleteCountry
      parameters:
        - name: pk
          in: path
          description: Country ID
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Country deleted successfully

  /api/tickets/:
    post:
      summary: Create a new ticket
      operationId: createTicket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_flight:
                  type: integer
                seat_number:
                  type: string
      responses:
        201:
          description: Ticket created successfully


  /api/tickets/{pk}/:
    get:
      summary: Get ticket details by ID
      operationId: ticketDetail
      parameters:
        - name: pk
          in: path
          description: Ticket ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful operation
    put:
      summary: Update ticket details
      operationId: updateTicket
      parameters:
        - name: pk
          in: path
          description: Ticket ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Ticket updated successfully
    delete:
      summary: Delete a ticket
      operationId: deleteTicket
      parameters:
        - name: pk
          in: path
          description: Ticket ID
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Ticket deleted successfully

  /api/aircrefts/:
    get:
      summary: Get a list of aircrafts
      operationId: aircraftList
      responses:
        200:
          description: Successful operation
    post:
      summary: Create a new aircraft
      operationId: createAircraft
      responses:
        201:
          description: Aircraft created successfully

  /api/aircrafts/{pk}/:
    get:
      summary: Get aircraft details by ID
      operationId: aircraftDetail
      parameters:
        - name: pk
          in: path
          description: Aircraft ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful operation
    put:
      summary: Update aircraft details
      operationId: updateAircraft
      parameters:
        - name: pk
          in: path
          description: Aircraft ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Aircraft updated successfully
    delete:
      summary: Delete an aircraft
      operationId: deleteAircraft
      parameters:
        - name: pk
          in: path
          description: Aircraft ID
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Aircraft deleted successfully

components:
  schemas:
    Country:
      type: object
      properties:
        id_country:
          type: integer
        name:
          type: string

    Flight:
      type: object
      properties:
        id_flight:
          type: integer
        country_source_id:
          type: integer
        country_target_id:
          type: integer
        id_air:
          type: integer
        departure_time:
          type: string
          format: date-time
        arrival_time:
          type: string
          format: date-time

    Aircraft:
      type: object
      properties:
        id_air:
          type: integer
        name:
          type: string
        count_sits:
          type: integer

    Ticket:
      type: object
      properties:
        id_ticket:
          type: integer
        id_flight:
          type: integer
        seat_number:
          type: integer
